<#
  Argus one-click installer.

  Run from an elevated PowerShell, or via:
    irm https://raw.githubusercontent.com/moshefurman/argus/main/install.ps1 | iex

  It downloads the latest release, sets up the Sysmon config Argus needs,
  installs the background service, and starts the local dashboard.
#>
[CmdletBinding()]
param(
  [string]$Repo       = 'moshefurman/argus',                 # <-- set to your GitHub user/org once
  [string]$Version    = 'latest',
  [string]$InstallDir = "$env:ProgramFiles\Argus",
  [int]   $Port       = 8080,
  [switch]$NoSysmon,                                    # skip Sysmon setup (already configured)
  [switch]$NoService                                    # install files only, don't run as a service
)

$ErrorActionPreference = 'Stop'
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

function Info($m) { Write-Host "==> $m" -ForegroundColor Cyan }
function Ok($m)   { Write-Host "    $m" -ForegroundColor Green }
function Warn($m) { Write-Host "    $m" -ForegroundColor Yellow }

# --- elevate if needed --------------------------------------------------------
$isAdmin = ([Security.Principal.WindowsPrincipal] `
  [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole(
  [Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $isAdmin) {
  Warn 'Administrator rights are required. Re-launching elevated...'
  $args = "-NoProfile -ExecutionPolicy Bypass -File `"$PSCommandPath`" -Repo `"$Repo`" -Port $Port"
  if ($NoSysmon)  { $args += ' -NoSysmon' }
  if ($NoService) { $args += ' -NoService' }
  Start-Process powershell -Verb RunAs -ArgumentList $args
  return
}

Info "Installing Argus into $InstallDir"
New-Item -ItemType Directory -Force -Path $InstallDir, "$InstallDir\data" | Out-Null

# --- download + extract the release ------------------------------------------
$asset = 'argus-windows-amd64.zip'
$url = if ($Version -eq 'latest') {
  "https://github.com/$Repo/releases/latest/download/$asset"
} else {
  "https://github.com/$Repo/releases/download/$Version/$asset"
}
$zip = Join-Path $env:TEMP $asset
Info "Downloading $url"
try {
  Invoke-WebRequest -Uri $url -OutFile $zip -UseBasicParsing
} catch {
  Warn "Download failed: $($_.Exception.Message)"
  Warn "Check that a release exists at https://github.com/$Repo/releases"
  return
}
Info 'Extracting'
Expand-Archive -Path $zip -DestinationPath $InstallDir -Force
Remove-Item $zip -Force -ErrorAction SilentlyContinue
$exe = Join-Path $InstallDir 'argus.exe'
if (-not (Test-Path $exe)) { throw "argus.exe not found in the release package" }
Ok 'Files installed'

# --- Sysmon config ------------------------------------------------------------
if (-not $NoSysmon) {
  Info 'Setting up Sysmon (the telemetry source Argus reads)'
  $sysmonCfg = Join-Path $InstallDir 'configs\sysmon\argus-sysmon.xml'
  $sysmon = (Get-Command Sysmon64.exe -ErrorAction SilentlyContinue).Source
  if (-not $sysmon) { $sysmon = (Get-Command Sysmon.exe -ErrorAction SilentlyContinue).Source }
  if (-not $sysmon) {
    Info 'Sysmon not found; downloading from Sysinternals'
    try {
      $sz = Join-Path $env:TEMP 'Sysmon.zip'
      Invoke-WebRequest 'https://download.sysinternals.com/files/Sysmon.zip' -OutFile $sz -UseBasicParsing
      Expand-Archive $sz -DestinationPath (Join-Path $InstallDir 'sysmon') -Force
      Remove-Item $sz -Force -ErrorAction SilentlyContinue
      $sysmon = Join-Path $InstallDir 'sysmon\Sysmon64.exe'
    } catch { Warn "Could not fetch Sysmon automatically: $($_.Exception.Message)" }
  }
  if ($sysmon -and (Test-Path $sysmonCfg)) {
    $installed = Get-Service -Name Sysmon64, Sysmon -ErrorAction SilentlyContinue
    if ($installed) { & $sysmon -accepteula -c $sysmonCfg | Out-Null; Ok 'Sysmon config updated' }
    else            { & $sysmon -accepteula -i $sysmonCfg | Out-Null; Ok 'Sysmon installed' }
    # audit subcategories used by the authentication detections
    foreach ($g in @('{0CCE9215-69AE-11D9-BED3-505054503030}',  # Logon
                     '{0CCE9217-69AE-11D9-BED3-505054503030}',  # Special Logon
                     '{0CCE9242-69AE-11D9-BED3-505054503030}')) { # Kerberos service ticket
      auditpol /set /subcategory:"$g" /success:enable /failure:enable | Out-Null
    }
  } else {
    Warn 'Skipped Sysmon setup (no Sysmon binary). Auth/credential detections need it configured.'
  }
}

# --- runtime config -----------------------------------------------------------
$cfg = Join-Path $InstallDir 'argus.yaml'
@"
# Generated by install.ps1
db: $InstallDir\data\argus.db
index: $InstallDir\data\argus.idx
addr: 127.0.0.1:$Port
live: true
notify: false            # the SYSTEM service can't show toasts; the user helper does (below)
patterns: $InstallDir\configs\malware\patterns
lowlevel: $InstallDir\configs\lolbin\lowlevel
hl: $InstallDir\configs\lolbin\hl
hql: $InstallDir\configs\lolbin\hql
"@ | Set-Content -Path $cfg -Encoding UTF8

# --- service + user notifier --------------------------------------------------
if (-not $NoService) {
  Info 'Installing the background service'
  & $exe service uninstall 2>$null | Out-Null
  & $exe service install --config $cfg
  & $exe service start
  Ok 'Service running'

  # Desktop toasts come from a lightweight per-user helper (session 0 can't toast).
  $runKey = 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Run'
  Set-ItemProperty -Path $runKey -Name 'ArgusNotify' `
    -Value "`"$exe`" notify-watch --addr 127.0.0.1:$Port"
  Start-Process -FilePath $exe -ArgumentList "notify-watch --addr 127.0.0.1:$Port" -WindowStyle Hidden
  Ok 'Desktop alerts enabled'
}

Write-Host ''
Ok "Argus is installed. Open your dashboard:"
Write-Host "    http://127.0.0.1:$Port" -ForegroundColor White
Write-Host ''
Write-Host "    Manage:  `"$exe`" service stop | start | uninstall" -ForegroundColor DarkGray
